### Pandas – Loading and Cleaning Data
Today, we'll learn to use **Pandas**, the most essential tool in a Python data scientist's toolkit, to take a raw,
messy dataset and turn it into a clean, reliable foundation for analysis.


1.  The Building Blocks:** What are Pandas `Series` and `DataFrames`?
2.  Getting the Data:** Reading CSV files and first-look inspection.
3.  The Cleaning Workflow:**
    *   Handling Missing Values (`NaN`)
    *   Finding and Removing Duplicates
    *   Correcting Data Types and Formatting
4.  Exporting Our Clean Data.**
Pandas is a Python library used to collect, organize, clean, manipulate, and analyze structured data efficiently.

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\HP ProBook\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\HP ProBook\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP ProBook\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HP ProBook\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\HP ProBook\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Series

## Create a Series Object from a List
- A pandas **Series** is a one-dimensional labelled array.
- A Series combines the best features of a list and a dictionary.
- A Series maintains a single collection of ordered values (i.e. a single column of data).
- We can assign each value an identifier, which does not have to *be* unique.

In [5]:
# creating the series from the list
ice_cream = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"]
pd.Series(ice_cream)

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: str

In [8]:
# pd.series() has second attribute index where we can send the index for the series
ice_cream = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"]
ice_cream = pd.Series(ice_cream, index = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"])
ice_cream

Chocolate      Chocolate
Vanilla          Vanilla
Strawberry    Strawberry
Rum Raisin    Rum Raisin
dtype: str

In [9]:
# accessing the series value through indexing
print(ice_cream["Chocolate"])

Chocolate

In [6]:
# creating the series containing integers 
lottery_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lottery_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [10]:
# creating the series containing booleans
registrations = [True, False, False, False, True]
pd.Series(registrations)

0     True
1    False
2    False
3    False
4     True
dtype: bool

## Create a Series Object from a Dictionary

In [11]:
# dictionary's keys becomes the index and the values becomes the value of the corresponding index in Series
sushi = {
    "Salmon": "Orange",
    "Tuna": "Red",
    "Eel": "Brown"
}

series_sushi = pd.Series(sushi)
series_sushi

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: str

In [12]:
dir(series_sushi)

['Eel',
 'Salmon',
 'T',
 'Tuna',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

## Intro to Series Methods
- The syntax to invoke a method on any object is `object.method()`.
- The `sum` method adds together the **Series'** values.
- The `product` method multiplies the **Series'** values.
- The `mean` method finds the average of the **Series'** values.
- The `std` method finds the standard deviation of the **Series'** values.

In [12]:
# making the series
prices = pd.Series([2.99, 4.45, 1.36])
prices

0    2.99
1    4.45
2    1.36
dtype: float64

In [13]:
# Finds the sum
prices.sum()

np.float64(8.8)

In [14]:
prices.product()

np.float64(18.095480000000006)

In [15]:
prices.mean()

np.float64(2.9333333333333336)

In [16]:
prices.std()

np.float64(1.5457791994115246)

## Intro to Attributes
- An **attribute** is a piece of data that lives on an object.
- An **attribute** is a fact, a detail, a characteristic of the object.
- Access an attribute with `object.attribute` syntax.
- The `size` attribute returns a count of the number of values in the **Series**.
- The `is_unique` attribute returns True if the **Series** has no duplicate values.
- The `values` and `index` attributes return the underlying objects that holds the **Series'** values and index labels.
- unique() returns the unique values themselves, while nunique() returns how many unique values there are

In [3]:
# creating another series
adjectives = pd.Series(["Smart", "Handsome", "Charming", "Brilliant", "Humble", "Smart"])
adjectives

0        Smart
1     Handsome
2     Charming
3    Brilliant
4       Humble
5        Smart
dtype: str

In [19]:

adjectives.size

6

In [20]:
adjectives.is_unique

False

In [4]:
# nunique() returns how many unique values there are
adjectives.nunique()

5

In [5]:
adjectives.values

<StringArray>
['Smart', 'Handsome', 'Charming', 'Brilliant', 'Humble', 'Smart']
Length: 6, dtype: str

In [6]:
adjectives.index

RangeIndex(start=0, stop=6, step=1)

## Parameters and Arguments
- A **parameter** is the name for an expected input to a function/method/class instantiation.
- An **argument** is the concrete value we provide for a parameter during invocation.
- We can pass arguments either sequentially (based on parameter order) or with explicit parameter names written out.
- The first two parameters for the **Series** constructor are `data` and `index`, which represent the values and the index labels.

In [7]:
# creating another two series from the list
fruits = ["Apple", "Orange", "Plum", "Grape", "Blueberry", "Watermelon"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Monday"]

In [26]:
print(pd.Series(fruits))
pd.Series(weekdays)

0         Apple
1        Orange
2          Plum
3         Grape
4     Blueberry
5    Watermelon
dtype: str

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5       Monday
dtype: str

In [8]:

a=pd.Series(fruits, weekdays)
print(a)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

In [9]:

b = pd.Series(weekdays, index=fruits)
print(b)

Apple            Monday
Orange          Tuesday
Plum          Wednesday
Grape          Thursday
Blueberry        Friday
Watermelon       Monday
dtype: str

In [10]:
print(pd.Series(data=fruits, index=weekdays))
pd.Series(index=weekdays, data=fruits)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

In [13]:
c = pd.Series(fruits, index=weekdays)
print(c)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

In [ ]:
# generally we always keeps the postional arguments at first and keyword arguments at last

In [32]:
pd.Series(fruits)

0         Apple
1        Orange
2          Plum
3         Grape
4     Blueberry
5    Watermelon
dtype: str

In [34]:
# empty series is created if the following code runs 
print(pd.Series())
pd.Series()

Series([], dtype: object)

Series([], dtype: object)

## Import Series with the pd.read_csv Function
- A **CSV** is a plain text file that uses line breaks to separate rows and commas to separate row values.
- Pandas ships with many different `read_` functions for different types of files.
- The `read_csv` function accepts many different parameters. The first one specifies the file name/path.
- The `read_csv` function will import the dataset as a **DataFrame**, a 2-dimensional table.
- The `usecols` parameter accepts a list of the column(s) to import.
- The `squeeze` method converts a **DataFrame** to a **Series**.

In [14]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

In [15]:
pokemon.size

1010

In [16]:
google = pd.read_csv("google_stock_price.csv", usecols=["1. open"]).squeeze("columns")
google

0       169.055
1       171.850
2       163.690
3       166.430
4       164.510
         ...
5220    104.760
5221    111.240
5222    110.760
5223    101.010
5224    100.010
Name: 1. open, Length: 5225, dtype: float64

## The head and tail Methods
- The `head` method returns a number of rows from the top/beginning of the `Series`.
- The `tail` method returns a number of rows from the bottom/end of the `Series`.

In [41]:
# pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
# google = pd.read_csv("google_stock_price.csv", usecols=["1. open"]).squeeze("columns")

In [43]:
print(pokemon.head())
print(pokemon.head(5))
print(pokemon.head(n=5))

print(pokemon.head(8))
print(pokemon.head(1))

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
7     Wartortle
Name: Name, dtype: str
0    Bulbasaur
Name: Name, dtype: str

In [17]:
print(google.tail())
print(google.tail(5))
print(google.tail(n=5))

print(google.tail(7))
print(google.tail(n=2))

5220    104.76
5221    111.24
5222    110.76
5223    101.01
5224    100.01
Name: 1. open, dtype: float64
5220    104.76
5221    111.24
5222    110.76
5223    101.01
5224    100.01
Name: 1. open, dtype: float64
5220    104.76
5221    111.24
5222    110.76
5223    101.01
5224    100.01
Name: 1. open, dtype: float64
5218    108.10
5219    104.95
5220    104.76
5221    111.24
5222    110.76
5223    101.01
5224    100.01
Name: 1. open, dtype: float64
5223    101.01
5224    100.01
Name: 1. open, dtype: float64

In [18]:
# sample funtion randomly chooses any of the value of the series and we can pass no. of samples we want in the argument
pokemon.sample(10)

1009    Iron Leaves
881       Dracovish
846     Barraskewda
234        Smeargle
62             Abra
568        Garbodor
26        Sandshrew
876         Morpeko
364         Walrein
270          Lombre
Name: Name, dtype: str

## Passing Series to Python's Built-In Functions
- The `len` function returns the length of the **Series**.
- The `type` function returns the type of an object.
- The `list` function converts the **Series** to a list.
- The `dict` function converts the **Series** to a dictionary.
- The `sorted` function converts the **Series** to a sorted list.
- The `max` function returns the largest value in the **Series**.
- The `min` function returns the smalllest value in the **Series**.

In [29]:
 # pandas series can use the python built in functions

In [49]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [50]:
len(pokemon)

1010

In [51]:
type(pokemon)

pandas.Series

In [19]:
list(pokemon.head())

['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon']

In [53]:
sorted(pokemon) # after sorting the series changes into list

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alcremie',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Annihilape',
 'Anorith',
 'Appletun',
 'Applin',
 'Araquanid',
 'Arbok',
 'Arboliva',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Arctibax',
 'Arctovish',
 'Arctozolt',
 'Ariados',
 'Armaldo',
 'Armarouge',
 'Aromatisse',
 'Aron',
 'Arrokuda',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Barraskewda',
 'Basculegion',
 'Basculin',
 'Bastiodon',
 'Baxcalibur',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellibolt',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bewear',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blacephalon',
 'Blastoise',
 'Blaziken',
 'Blipbug',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Boltund',
 'Bombirdier',
 'Bonsly',
 'Bouffalant',
 'Bounsweet',
 'Braixen',
 'Brambleghast',
 'Bramblin',
 'Braviary',
 'Breloom',
 'Brionne',
 'Bronzong',
 'Bronzor',
 'Brute Bonnet',
 'Bruxish',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Buzzwole',
 'Cacnea',
 'Cacturne',
 'Calyrex',
 'Camerupt',
 'Capsakid',
 'Carbink',
 'Carkol',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Celesteela',
 'Centiskorch',
 'Ceruledge',
 'Cetitan',
 'Cetoddle',
 'Chandelure',
 'Chansey',
 'Charcadet',
 'Charizard',
 'Charjabug',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chewtle',
 'Chi-Yu',
 'Chien-Pao',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Cinderace',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Clobbopus',
 'Clodsire',
 'Cloyster',
 'Coalossal',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Comfey',
 'Conkeldurr',
 'Copperajah',
 'Corphish',
 'Corsola',
 'Corviknight',
 'Corvisquire',
 'Cosmoem',
 'Cosmog',
 'Cottonee',
 'Crabominable',
 'Crabrawler',
 'Cradily',
 'Cramorant',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Crocalor',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cufant',
 'Cursola',
 'Cutiefly',
 'Cyclizar',
 'Cyndaquil',
 'Dachsbun',
 'Darkrai',
 'Darmanitan',
 'Dartrix',
 'Darumaka',
 'Decidueye',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dewpider',
 'Dhelmise',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Dolliv',
 'Dondozo',
 'Donphan',
 'Dottler',
 'Doublade',
 'Dracovish',
 'Dracozolt',
 'Dragalge',
 'Dragapult',
 'Dragonair',
 'Dragonite',
 'Drakloak',
 'Drampa',
 'Drapion',
 'Dratini',
 'Drednaw',
 'Dreepy',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drizzile',
 'Drowzee',
 'Druddigon',
 'Dubwool',
 'Ducklett',
 'Dudunsparce',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Duraludon',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Eiscue',
 'Ekans',
 'Eldegoss',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Enamorus',
 'Entei',
 'Escavalier',
 'Espathra',
 'Espeon',
 'Espurr',
 'Eternatus',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 'Falinks',
 'Farfetch’d',
 'Farigiraf',
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Fidough',
 'Finizen',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flamigo',
 'Flapple',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Flittle',
 'Floatzel',
 'Floette',
 'Floragato',
 'Florges',
 'Flutter Mane',
 'Flygon',
 'Fomantis',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frigibax',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Frosmoth',
 'Fuecoco',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Garganacl',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gholdengo',
 'Gible',
 'Gigalith',
 'Gimmighoul',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Glastrier',
 'Gligar',
 'Glimmet',
 'Glimmora',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golisopod',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gossifleur',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Grafaiai',
 'Granbull',
 'Grapploct',
 'Graveler',
 'Great Tusk',
 'Greavard',
 'Greedent',
 'Greninja',
 'Grimer',
 'Grimmsnarl',
 'Grookey',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grubbin',
 'Grumpig',
 'Gulpin',
 'Gumshoos',
 'Gurdurr',
 'Guzzlord',
 'Gyarados',
 'Hakamo-o',
 'Happiny',
 'Hariyama',
 'Hatenna',
 'Hatterene',
 'Hattrem',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-Oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Houndstone',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Impidimp',
 'Incineroar',
 'Indeedee',
 'Infernape',
 'Inkay',
 'Inteleon',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Leaves',
 'Iron Moth',
 'Iron Thorns',
 'Iron Treads',
 'Iron Valiant',
 'Ivysaur',
 'Jangmo-o',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kartana',
 'Kecleon',
 'Keldeo',
 'Kilowattrel',
 'Kingambit',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klawf',
 'Kleavor',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Komala',
 'Kommo-o',
 'Koraidon',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kubfu',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Lechonk',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litten',
 'Litwick',
 'Lokix',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunala',
 'Lunatone',
 'Lurantis',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Lycanroc',
 'Mabosstiff',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magearna',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareanie',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshadow',
 'Marshtomp',
 'Maschiff',
 'Masquerain',
 'Maushold',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Melmetal',
 'Meloetta',
 'Meltan',
 'Meowscarada',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milcery',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Mimikyu',
 'Minccino',
 'Minior',
 'Minun',
 'Miraidon',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Morelull',
 'Morgrem',
 'Morpeko',
 'Mothim',
 'Mr. Mime',
 'Mr. Rime',
 'Mudbray',
 'Mudkip',
 'Mudsdale',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Nacli',
 'Naclstack',
 'Naganadel',
 'Natu',
 'Necrozma',
 'Nickit',
 'Nidoking',
 'Nidoqueen',
 'Nidoran♀',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nihilego',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Nymble',
 'Obstagoon',
 'Octillery',
 'Oddish',
 'Oinkologne',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oranguru',
 'Orbeetle',
 'Oricorio',
 'Orthworm',
 'Oshawott',
 'Overqwil',
 'Pachirisu',
 'Palafin',
 'Palkia',
 'Palossand',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Passimian',
 'Patrat',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Pawniard',
 'Pelipper',
 'Perrserker',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Pheromosa',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Pikipek',
 'Piloswine',
 'Pincurchin',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Poipole',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Polteageist',
 'Ponyta',
 'Poochyena',
 'Popplio',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primarina',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Pyukumuku',
 'Quagsire',
 'Quaquaval',
 'Quaxly',
 'Quaxwell',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raboot',
 'Rabsca',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regidrago',
 'Regieleki',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Rellor',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Revavroom',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Ribombee',
 'Rillaboom',
 'Riolu',
 'Roaring Moon',
 'Rockruff',
 'Roggenrola',
 'Rolycoly',
 'Rookidee',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rowlet',
 'Rufflet',
 'Runerigus',
 'Sableye',
 'Salamence',
 'Salandit',
 'Salazzle',
 'Samurott',
 'Sandaconda',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sandy Shocks',
 'Sandygast',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scorbunny',
 'Scovillain',
 'Scrafty',
 'Scraggy',
 'Scream Tail',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shiinotic',
 'Shinx',
 'Shroodle',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Silicobra',
 'Silvally',
 'Simipour',
 'Simisage',
 'Simisear',
 'Sinistea',
 'Sirfetch’d',
 'Sizzlipede',
 'Skarmory',
 'Skeledirge',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Skwovet',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slither Wing',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoliv',
 'Smoochum',
 'Sneasel',
 'Sneasler',
 'Snivy',
 'Snom',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Sobble',
 'Solgaleo',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spectrier',
 'Spewpa',
 'Spheal',
 'Spidops',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Sprigatito',
 'Spritzee',
 'Squawkabilly',
 'Squirtle',
 'Stakataka',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Steenee',
 'Stonjourner',
 'Stoutland',
 'Stufful',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Tadbulb',
 'Taillow',
 'Talonflame',
 'Tandemaus',
 'Tangela',
 'Tangrowth',
 'Tapu Bulu',
 'Tapu Fini',
 'Tapu Koko',
 'Tapu Lele',
 'Tarountula',
 'Tatsugiri',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Thievul',
 'Throh',
 'Thundurus',
 'Thwackey',
 'Timburr',
 'Ting-Lu',
 'Tinkatink',
 'Tinkaton',
 'Tinkatuff',
 'Tirtouga',
 'Toedscool',
 'Toedscruel',
 'Togedemaru',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torracat',
 'Torterra',
 'Totodile',
 'Toucannon',
 'Toxapex',
 'Toxel',
 'Toxicroak',
 'Toxtricity',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Trumbeak',
 'Tsareena',
 'Turtonator',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Type: Null',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaluna',
 'Ursaring',
 'Urshifu',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Varoom',
 'Veluza',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vikavolt',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walking Wake',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Wattrel',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wiglett',
 'Wimpod',
 'Wingull',
 'Wishiwashi',
 'Wo-Chien',
 'Wobbuffet',
 'Woobat',
 'Wooloo',
 'Wooper',
 'Wormadam',
 'Wugtrio',
 'Wurmple',
 'Wynaut',
 'Wyrdeer',
 'Xatu',
 'Xerneas',
 'Xurkitree',
 'Yamask',
 'Yamper',
 'Yanma',
 'Yanmega',
 'Yungoos',
 'Yveltal',
 'Zacian',
 'Zamazenta',
 'Zangoose',
 'Zapdos',
 ...]

In [54]:
type(sorted(pokemon))

list

In [55]:
sorted(google)

[85.4,
 85.98,
 86.32,
 86.62,
 86.79,
 86.98,
 86.98,
 87.11,
 87.28,
 87.47,
 88.11,
 88.16,
 88.36,
 88.45,
 88.795,
 88.9,
 89.08,
 89.18,
 89.33,
 89.44,
 89.585,
 89.66,
 89.87,
 89.98,
 90.09,
 90.255,
 90.35,
 90.72,
 90.76,
 90.85,
 90.94,
 91.48,
 91.7,
 91.92,
 92.06,
 92.14,
 92.17,
 92.25,
 92.27,
 92.48,
 92.56,
 92.71,
 93.0,
 93.13,
 93.22,
 93.77,
 94.015,
 94.05,
 94.12,
 94.43,
 94.49,
 94.52,
 94.69,
 94.74,
 94.82,
 94.85,
 94.98,
 95.09,
 95.1,
 95.15,
 95.2,
 95.37,
 95.38,
 95.42,
 95.45,
 95.45,
 95.57,
 95.73,
 95.95,
 96.2,
 96.41,
 96.43,
 96.5,
 96.76,
 96.87,
 96.97,
 97.0363,
 97.05,
 97.09,
 97.29,
 97.3,
 97.31,
 97.43,
 97.48,
 97.65,
 97.76,
 97.845,
 97.9,
 97.95,
 98.1,
 98.1,
 98.24,
 98.26,
 98.64,
 98.71,
 98.77,
 98.82,
 98.86,
 99.0,
 99.05,
 99.09,
 99.3,
 99.4,
 99.43,
 99.63,
 99.825,
 99.85,
 99.99,
 100.0,
 100.0,
 100.01,
 100.01,
 100.12,
 100.26,
 100.44,
 100.68,
 100.74,
 100.91,
 100.95,
 101.01,
 101.01,
 101.02,
 101.25,
 101.3,
 101.47,
 101.67,
 101.75,
 101.8,
 102.05,
 102.07,
 102.08,
 102.28,
 102.32,
 102.39,
 102.4,
 102.44,
 102.5,
 102.7,
 102.9,
 102.93,
 103.13,
 103.22,
 103.58,
 103.91,
 104.03,
 104.27,
 104.33,
 104.45,
 104.57,
 104.615,
 104.658,
 104.76,
 104.82,
 104.92,
 104.95,
 104.99,
 105.06,
 105.18,
 105.26,
 105.28,
 105.47,
 105.485,
 105.49,
 105.53,
 105.78,
 105.8,
 105.825,
 105.84,
 106.49,
 106.55,
 106.58,
 106.6,
 106.63,
 106.84,
 106.89,
 106.98,
 107.04,
 107.06,
 107.14,
 107.3,
 107.44,
 107.8,
 107.97,
 108.04,
 108.1,
 108.28,
 108.39,
 108.41,
 109.065,
 109.26,
 109.99,
 110.17,
 110.56,
 110.59,
 110.65,
 110.76,
 110.85,
 110.99,
 111.0,
 111.24,
 112.34,
 112.37,
 112.64,
 113.08,
 113.17,
 113.475,
 113.5,
 114.0,
 114.235,
 114.28,
 114.42,
 114.72,
 115.2,
 115.3,
 115.395,
 115.71,
 116.11,
 116.23,
 116.29,
 116.49,
 116.68,
 116.95,
 117.08,
 117.09,
 117.135,
 117.45,
 117.48,
 118.3,
 118.39,
 118.78,
 118.8,
 118.84,
 119.06,
 119.24,
 119.24,
 119.24,
 119.43,
 119.56,
 119.61,
 119.795,
 120.0,
 120.1,
 120.12,
 120.17,
 120.2,
 120.26,
 120.62,
 120.76,
 120.93,
 120.95,
 120.97,
 121.12,
 121.13,
 121.15,
 121.28,
 121.36,
 121.38,
 121.42,
 121.52,
 121.66,
 122.225,
 122.25,
 122.4,
 122.75,
 122.785,
 122.815,
 122.88,
 122.93,
 122.94,
 123.1,
 123.14,
 123.17,
 123.21,
 123.27,
 123.55,
 123.99,
 124.01,
 124.07,
 124.16,
 124.52,
 124.6,
 124.6,
 124.8,
 124.98,
 125.06,
 125.64,
 125.93,
 125.94,
 126.01,
 126.53,
 126.97,
 127.175,
 127.97,
 128.02,
 128.16,
 128.42,
 128.51,
 128.51,
 128.57,
 128.66,
 128.7,
 128.95,
 129.05,
 129.16,
 129.28,
 129.39,
 129.45,
 129.54,
 129.77,
 129.8,
 129.83,
 129.84,
 129.88,
 129.899,
 130.07,
 130.105,
 130.18,
 130.62,
 130.71,
 130.76,
 130.775,
 130.78,
 130.8,
 130.97,
 131.1,
 131.21,
 131.31,
 131.32,
 131.44,
 131.44,
 131.62,
 131.66,
 131.67,
 131.78,
 131.81,
 131.86,
 131.88,
 131.96,
 132.24,
 132.38,
 132.63,
 132.73,
 132.79,
 132.795,
 133.12,
 133.28,
 133.38,
 133.38,
 133.59,
 133.69,
 133.94,
 133.95,
 134.01,
 134.19,
 134.2,
 134.21,
 134.49,
 134.66,
 134.78,
 134.87,
 134.91,
 135.04,
 135.04,
 135.05,
 135.07,
 135.09,
 135.19,
 135.275,
 135.44,
 135.66,
 136.0,
 136.01,
 136.02,
 136.03,
 136.08,
 136.13,
 136.26,
 136.29,
 136.29,
 136.54,
 136.56,
 136.61,
 136.745,
 136.84,
 136.94,
 137.01,
 137.03,
 137.25,
 137.28,
 137.33,
 137.42,
 137.455,
 137.47,
 137.57,
 137.6,
 137.67,
 137.83,
 137.9,
 137.98,
 138.02,
 138.03,
 138.08,
 138.17,
 138.42,
 138.43,
 138.5,
 138.5,
 138.5,
 138.55,
 138.58,
 138.63,
 138.73,
 138.97,
 139.0,
 139.26,
 139.38,
 139.445,
 139.49,
 139.63,
 139.655,
 140.77,
 140.78,
 141.0,
 141.02,
 141.05,
 141.19,
 141.345,
 141.45,
 141.55,
 141.59,
 141.59,
 142.0,
 142.05,
 142.12,
 142.14,
 142.5,
 142.67,
 142.82,
 142.99,
 143.12,
 143.14,
 143.24,
 143.49,
 143.62,
 143.67,
 144.13,
 144.415,
 144.65,
 144.74,
 144.76,
 144.92,
 144.93,
 144.95,
 145.83,
 145.89,
 146.08,
 146.68,
 147.1,
 147.94,
 148.0,
 148.01,
 148.16,
 148.42,
 148.54,
 148.61,
 148.88,
 148.89,
 149.12,
 149.47,
 149.92,
 149.94,
 150.03,
 150.065,
 150.22,
 150.45,
 150.5,
 150.69,
 150.85,
 151.1,
 151.11,
 151.18,
 151.22,
 151.33,
 152.06,
 152.51,
 152.78,
 152.8,
 152.9,
 153.1,
 153.11,
 153.5,
 153.5,
 153.6,
 153.62,
 153.8,
 154.17,
 154.19,
 154.29,
 154.31,
 155.0,
 155.15,
 155.34,
 155.43,
 155.5,
 155.61,
 155.62,
 156.085,
 156.15,
 156.2,
 156.21,
 156.3,
 156.54,
 156.655,
 156.91,
 156.96,
 157.3,
 157.31,
 157.485,
 157.49,
 157.96,
 157.975,
 158.79,
 158.86,
 159.02,
 159.125,
 159.33,
 159.86,
 159.96,
 159.995,
 160.01,
 160.325,
 160.45,
 160.49,
 160.5,
 160.51,
 160.87,
 161.205,
 161.25,
 161.47,
 161.47,
 161.57,
 161.72,
 161.76,
 162.13,
 162.17,
 162.4,
 162.425,
 162.615,
 162.81,
 162.83,
 162.95,
 162.98,
 163.0,
 163.03,
 163.19,
 163.27,
 163.32,
 163.405,
 163.41,
 163.45,
 163.5,
 163.64,
 163.64,
 163.67,
 163.675,
 163.69,
 163.71,
 163.94,
 164.08,
 164.26,
 164.3,
 164.31,
 164.35,
 164.35,
 164.41,
 164.51,
 164.53,
 164.63,
 164.72,
 164.76,
 164.785,
 164.91,
 165.03,
 165.035,
 165.07,
 165.15,
 165.28,
 165.612,
 165.73,
 165.785,
 165.835,
 165.84,
 165.85,
 166.035,
 166.09,
 166.24,
 166.38,
 166.42,
 166.43,
 166.44,
 166.58,
 166.9,
 167.065,
 167.15,
 167.26,
 167.46,
 167.56,
 167.63,
 167.685,
 167.72,
 167.725,
 167.73,
 167.915,
 168.025,
 168.06,
 168.26,
 168.5,
 168.5,
 168.6,
 168.68,
 168.75,
 168.765,
 168.83,
 168.98,
 169.0,
 169.0,
 169.0,
 169.02,
 169.055,
 169.058,
 169.06,
 169.32,
 169.39,
 169.43,
 169.77,
 169.93,
 170.07,
 170.24,
 170.25,
 170.25,
 170.4,
 170.435,
 170.52,
 170.53,
 170.57,
 170.63,
 170.67,
 170.86,
 171.0,
 171.145,
 171.26,
 171.49,
 171.85,
 171.86,
 171.925,
 172.03,
 172.03,
 172.52,
 172.54,
 173.13,
 173.24,
 173.28,
 173.29,
 173.42,
 173.43,
 173.6,
 173.72,
 173.73,
 173.8,
 173.9,
 173.96,
 173.99,
 174.1,
 174.18,
 174.22,
 174.37,
 174.39,
 174.45,
 174.84,
 174.97,
 174.98,
 175.07,
 175.2,
 175.2,
 175.25,
 175.36,
 175.37,
 175.43,
 175.46,
 175.8,
 175.895,
 176.0,
 176.11,
 176.192,
 176.22,
 176.28,
 176.644,
 176.7,
 176.76,
 176.9,
 177.0,
 177.05,
 177.07,
 177.13,
 177.14,
 177.22,
 177.34,
 177.41,
 177.95,
 177.97,
 177.99,
 178.04,
 178.25,
 178.28,
 178.33,
 178.58,
 178.81,
 178.88,
 179.13,
 179.27,
 179.27,
 179.62,
 179.82,
 179.9,
 179.95,
 180.0,
 180.16,
 180.228,
 180.255,
 180.44,
 180.45,
 180.46,
 180.59,
 180.64,
 180.645,
 180.68,
 180.7,
 181.01,
 181.05,
 181.18,
 181.68,
 181.76,
 181.77,
 181.93,
 181.99,
 182.0,
 182.0,
 182.05,
 182.05,
 182.2,
 182.509,
 182.63,
 182.845,
 182.965,
 183.03,
 183.22,
 183.37,
 183.9,
 184.07,
 184.18,
 184.21,
 184.32,
 184.32,
 184.58,
 184.8,
 184.85,
 184.92,
 185.03,
 185.055,
 185.08,
 185.15,
 185.23,
 185.31,
 185.6,
 185.78,
 185.855,
 185.95,
 186.0,
 186.08,
 186.13,
 186.28,
 186.449,
 186.63,
 186.66,
 186.7,
 187.35,
 187.36,
 187.45,
 187.73,
 187.78,
 188.25,
 188.69,
 188.76,
 188.78,
 189.1,
 189.15,
 189.15,
 189.24,
 189.29,
 189.33,
 189.43,
 189.5,
 189.8,
 189.845,
 189.895,
 190.07,
 190.1,
 190.13,
 190.31,
 190.64,
 190.65,
 191.01,
 191.05,
 191.07,
 191.075,
 191.24,
 191.37,
 191.625,
 191.97,
 191.97,
 192.11,
 192.41,
 192.57,
 192.58,
 192.62,
 192.745,
 192.87,
 192.97,
 193.0,
 193.09,
 193.09,
 193.27,
 193.3,
 193.45,
 193.47,
 193.5,
 193.605,
 193.69,
 193.69,
 193.98,
 194.14,
 194.295,
 194.33,
 194.38,
 194.44,
 194.5,
 194.7,
 194.84,
 194.95,
 195.0,
 195.15,
 195.22,
 195.25,
 195.38,
 195.555,
 195.62,
 196.0,
 196.5,
 196.53,
 196.96,
 197.11,
 197.25,
 197.4,
 197.83,
 198.0,
 198.1,
 198.14,
 198.19,
 198.51,
 198.58,
 198.73,
 198.87,
 199.06,
 199.07,
 199.23,
 200.42,
 200.69,
 200.76,
 200.89,
 201.33,
 202.0,
 203.39,
 204.64,
 205.26,
 205.99,
 206.47,
 215.55,
 217.82,
 217.99,
 219.5,
 220.22,
 221.54,
 221.91,
 222.05,
 222.905,
 225.47,
 227.18,
 228.0,
 228.4,
 228.62,
 228.9,
 229.18,
 229.68,
 230.56,
 230.81,
 233.61,
 240.48,
 241.21,
 243.16,
 252.73,
 256.96,
 260.48,
 260.96,
 262.51,
 268.68,
 269.26,
 269.56,
 269.73,
 269.85,
 271.02,
 274.26,
 274.89,
 275.0,
 275.91,
 276.08,
 276.16,
 276.53,
 277.57,
 278.59,
 279.0,
 279.82,
 280.28,
 280.99,
 281.24,
 282.24,
 282.39,
 282.55,
 283.2,
 283.36,
 283.48,
 284.72,
 284.88,
 285.51,
 285.89,
 285.89,
 285.91,
 286.51,
 286.68,
 286.79,
 286.99,
 287.22,
 288.0,
 288.18,
 288.23,
 288.48,
 288.73,
 289.0,
 289.39,
 289.67,
 289.79,
 289.98,
 289.99,
 290.58,
 290.9,
 291.3,
 291.6,
 291.77,
 291.96,
 292.0,
 292.14,
 292.51,
 292.85,
 293.39,
 293.6,
 294.34,
 294.83,
 295.01,
 295.04,
 295.39,
 295.55,
 295.71,
 296.25,
 296.4,
 297.1,
 297.2,
 297.28,
 297.3,
 297.5,
 297.5,
 297.57,
 297.69,
 297.74,
 298.0,
 298.04,
 298.25,
 298.9,
 299.14,
 299.26,
 299.646,
 299.8,
 ...]

In [20]:
# making the pokemon dictionary
dict(pokemon)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'Charmander',
 4: 'Charmeleon',
 5: 'Charizard',
 6: 'Squirtle',
 7: 'Wartortle',
 8: 'Blastoise',
 9: 'Caterpie',
 10: 'Metapod',
 11: 'Butterfree',
 12: 'Weedle',
 13: 'Kakuna',
 14: 'Beedrill',
 15: 'Pidgey',
 16: 'Pidgeotto',
 17: 'Pidgeot',
 18: 'Rattata',
 19: 'Raticate',
 20: 'Spearow',
 21: 'Fearow',
 22: 'Ekans',
 23: 'Arbok',
 24: 'Pikachu',
 25: 'Raichu',
 26: 'Sandshrew',
 27: 'Sandslash',
 28: 'Nidoran♀',
 29: 'Nidorina',
 30: 'Nidoqueen',
 31: 'Nidoran♂',
 32: 'Nidorino',
 33: 'Nidoking',
 34: 'Clefairy',
 35: 'Clefable',
 36: 'Vulpix',
 37: 'Ninetales',
 38: 'Jigglypuff',
 39: 'Wigglytuff',
 40: 'Zubat',
 41: 'Golbat',
 42: 'Oddish',
 43: 'Gloom',
 44: 'Vileplume',
 45: 'Paras',
 46: 'Parasect',
 47: 'Venonat',
 48: 'Venomoth',
 49: 'Diglett',
 50: 'Dugtrio',
 51: 'Meowth',
 52: 'Persian',
 53: 'Psyduck',
 54: 'Golduck',
 55: 'Mankey',
 56: 'Primeape',
 57: 'Growlithe',
 58: 'Arcanine',
 59: 'Poliwag',
 60: 'Poliwhirl',
 61: 'Poliwrath',
 62: 'Abra',
 63: 'Kadabra',
 64: 'Alakazam',
 65: 'Machop',
 66: 'Machoke',
 67: 'Machamp',
 68: 'Bellsprout',
 69: 'Weepinbell',
 70: 'Victreebel',
 71: 'Tentacool',
 72: 'Tentacruel',
 73: 'Geodude',
 74: 'Graveler',
 75: 'Golem',
 76: 'Ponyta',
 77: 'Rapidash',
 78: 'Slowpoke',
 79: 'Slowbro',
 80: 'Magnemite',
 81: 'Magneton',
 82: 'Farfetch’d',
 83: 'Doduo',
 84: 'Dodrio',
 85: 'Seel',
 86: 'Dewgong',
 87: 'Grimer',
 88: 'Muk',
 89: 'Shellder',
 90: 'Cloyster',
 91: 'Gastly',
 92: 'Haunter',
 93: 'Gengar',
 94: 'Onix',
 95: 'Drowzee',
 96: 'Hypno',
 97: 'Krabby',
 98: 'Kingler',
 99: 'Voltorb',
 100: 'Electrode',
 101: 'Exeggcute',
 102: 'Exeggutor',
 103: 'Cubone',
 104: 'Marowak',
 105: 'Hitmonlee',
 106: 'Hitmonchan',
 107: 'Lickitung',
 108: 'Koffing',
 109: 'Weezing',
 110: 'Rhyhorn',
 111: 'Rhydon',
 112: 'Chansey',
 113: 'Tangela',
 114: 'Kangaskhan',
 115: 'Horsea',
 116: 'Seadra',
 117: 'Goldeen',
 118: 'Seaking',
 119: 'Staryu',
 120: 'Starmie',
 121: 'Mr. Mime',
 122: 'Scyther',
 123: 'Jynx',
 124: 'Electabuzz',
 125: 'Magmar',
 126: 'Pinsir',
 127: 'Tauros',
 128: 'Magikarp',
 129: 'Gyarados',
 130: 'Lapras',
 131: 'Ditto',
 132: 'Eevee',
 133: 'Vaporeon',
 134: 'Jolteon',
 135: 'Flareon',
 136: 'Porygon',
 137: 'Omanyte',
 138: 'Omastar',
 139: 'Kabuto',
 140: 'Kabutops',
 141: 'Aerodactyl',
 142: 'Snorlax',
 143: 'Articuno',
 144: 'Zapdos',
 145: 'Moltres',
 146: 'Dratini',
 147: 'Dragonair',
 148: 'Dragonite',
 149: 'Mewtwo',
 150: 'Mew',
 151: 'Chikorita',
 152: 'Bayleef',
 153: 'Meganium',
 154: 'Cyndaquil',
 155: 'Quilava',
 156: 'Typhlosion',
 157: 'Totodile',
 158: 'Croconaw',
 159: 'Feraligatr',
 160: 'Sentret',
 161: 'Furret',
 162: 'Hoothoot',
 163: 'Noctowl',
 164: 'Ledyba',
 165: 'Ledian',
 166: 'Spinarak',
 167: 'Ariados',
 168: 'Crobat',
 169: 'Chinchou',
 170: 'Lanturn',
 171: 'Pichu',
 172: 'Cleffa',
 173: 'Igglybuff',
 174: 'Togepi',
 175: 'Togetic',
 176: 'Natu',
 177: 'Xatu',
 178: 'Mareep',
 179: 'Flaaffy',
 180: 'Ampharos',
 181: 'Bellossom',
 182: 'Marill',
 183: 'Azumarill',
 184: 'Sudowoodo',
 185: 'Politoed',
 186: 'Hoppip',
 187: 'Skiploom',
 188: 'Jumpluff',
 189: 'Aipom',
 190: 'Sunkern',
 191: 'Sunflora',
 192: 'Yanma',
 193: 'Wooper',
 194: 'Quagsire',
 195: 'Espeon',
 196: 'Umbreon',
 197: 'Murkrow',
 198: 'Slowking',
 199: 'Misdreavus',
 200: 'Unown',
 201: 'Wobbuffet',
 202: 'Girafarig',
 203: 'Pineco',
 204: 'Forretress',
 205: 'Dunsparce',
 206: 'Gligar',
 207: 'Steelix',
 208: 'Snubbull',
 209: 'Granbull',
 210: 'Qwilfish',
 211: 'Scizor',
 212: 'Shuckle',
 213: 'Heracross',
 214: 'Sneasel',
 215: 'Teddiursa',
 216: 'Ursaring',
 217: 'Slugma',
 218: 'Magcargo',
 219: 'Swinub',
 220: 'Piloswine',
 221: 'Corsola',
 222: 'Remoraid',
 223: 'Octillery',
 224: 'Delibird',
 225: 'Mantine',
 226: 'Skarmory',
 227: 'Houndour',
 228: 'Houndoom',
 229: 'Kingdra',
 230: 'Phanpy',
 231: 'Donphan',
 232: 'Porygon2',
 233: 'Stantler',
 234: 'Smeargle',
 235: 'Tyrogue',
 236: 'Hitmontop',
 237: 'Smoochum',
 238: 'Elekid',
 239: 'Magby',
 240: 'Miltank',
 241: 'Blissey',
 242: 'Raikou',
 243: 'Entei',
 244: 'Suicune',
 245: 'Larvitar',
 246: 'Pupitar',
 247: 'Tyranitar',
 248: 'Lugia',
 249: 'Ho-Oh',
 250: 'Celebi',
 251: 'Treecko',
 252: 'Grovyle',
 253: 'Sceptile',
 254: 'Torchic',
 255: 'Combusken',
 256: 'Blaziken',
 257: 'Mudkip',
 258: 'Marshtomp',
 259: 'Swampert',
 260: 'Poochyena',
 261: 'Mightyena',
 262: 'Zigzagoon',
 263: 'Linoone',
 264: 'Wurmple',
 265: 'Silcoon',
 266: 'Beautifly',
 267: 'Cascoon',
 268: 'Dustox',
 269: 'Lotad',
 270: 'Lombre',
 271: 'Ludicolo',
 272: 'Seedot',
 273: 'Nuzleaf',
 274: 'Shiftry',
 275: 'Taillow',
 276: 'Swellow',
 277: 'Wingull',
 278: 'Pelipper',
 279: 'Ralts',
 280: 'Kirlia',
 281: 'Gardevoir',
 282: 'Surskit',
 283: 'Masquerain',
 284: 'Shroomish',
 285: 'Breloom',
 286: 'Slakoth',
 287: 'Vigoroth',
 288: 'Slaking',
 289: 'Nincada',
 290: 'Ninjask',
 291: 'Shedinja',
 292: 'Whismur',
 293: 'Loudred',
 294: 'Exploud',
 295: 'Makuhita',
 296: 'Hariyama',
 297: 'Azurill',
 298: 'Nosepass',
 299: 'Skitty',
 300: 'Delcatty',
 301: 'Sableye',
 302: 'Mawile',
 303: 'Aron',
 304: 'Lairon',
 305: 'Aggron',
 306: 'Meditite',
 307: 'Medicham',
 308: 'Electrike',
 309: 'Manectric',
 310: 'Plusle',
 311: 'Minun',
 312: 'Volbeat',
 313: 'Illumise',
 314: 'Roselia',
 315: 'Gulpin',
 316: 'Swalot',
 317: 'Carvanha',
 318: 'Sharpedo',
 319: 'Wailmer',
 320: 'Wailord',
 321: 'Numel',
 322: 'Camerupt',
 323: 'Torkoal',
 324: 'Spoink',
 325: 'Grumpig',
 326: 'Spinda',
 327: 'Trapinch',
 328: 'Vibrava',
 329: 'Flygon',
 330: 'Cacnea',
 331: 'Cacturne',
 332: 'Swablu',
 333: 'Altaria',
 334: 'Zangoose',
 335: 'Seviper',
 336: 'Lunatone',
 337: 'Solrock',
 338: 'Barboach',
 339: 'Whiscash',
 340: 'Corphish',
 341: 'Crawdaunt',
 342: 'Baltoy',
 343: 'Claydol',
 344: 'Lileep',
 345: 'Cradily',
 346: 'Anorith',
 347: 'Armaldo',
 348: 'Feebas',
 349: 'Milotic',
 350: 'Castform',
 351: 'Kecleon',
 352: 'Shuppet',
 353: 'Banette',
 354: 'Duskull',
 355: 'Dusclops',
 356: 'Tropius',
 357: 'Chimecho',
 358: 'Absol',
 359: 'Wynaut',
 360: 'Snorunt',
 361: 'Glalie',
 362: 'Spheal',
 363: 'Sealeo',
 364: 'Walrein',
 365: 'Clamperl',
 366: 'Huntail',
 367: 'Gorebyss',
 368: 'Relicanth',
 369: 'Luvdisc',
 370: 'Bagon',
 371: 'Shelgon',
 372: 'Salamence',
 373: 'Beldum',
 374: 'Metang',
 375: 'Metagross',
 376: 'Regirock',
 377: 'Regice',
 378: 'Registeel',
 379: 'Latias',
 380: 'Latios',
 381: 'Kyogre',
 382: 'Groudon',
 383: 'Rayquaza',
 384: 'Jirachi',
 385: 'Deoxys',
 386: 'Turtwig',
 387: 'Grotle',
 388: 'Torterra',
 389: 'Chimchar',
 390: 'Monferno',
 391: 'Infernape',
 392: 'Piplup',
 393: 'Prinplup',
 394: 'Empoleon',
 395: 'Starly',
 396: 'Staravia',
 397: 'Staraptor',
 398: 'Bidoof',
 399: 'Bibarel',
 400: 'Kricketot',
 401: 'Kricketune',
 402: 'Shinx',
 403: 'Luxio',
 404: 'Luxray',
 405: 'Budew',
 406: 'Roserade',
 407: 'Cranidos',
 408: 'Rampardos',
 409: 'Shieldon',
 410: 'Bastiodon',
 411: 'Burmy',
 412: 'Wormadam',
 413: 'Mothim',
 414: 'Combee',
 415: 'Vespiquen',
 416: 'Pachirisu',
 417: 'Buizel',
 418: 'Floatzel',
 419: 'Cherubi',
 420: 'Cherrim',
 421: 'Shellos',
 422: 'Gastrodon',
 423: 'Ambipom',
 424: 'Drifloon',
 425: 'Drifblim',
 426: 'Buneary',
 427: 'Lopunny',
 428: 'Mismagius',
 429: 'Honchkrow',
 430: 'Glameow',
 431: 'Purugly',
 432: 'Chingling',
 433: 'Stunky',
 434: 'Skuntank',
 435: 'Bronzor',
 436: 'Bronzong',
 437: 'Bonsly',
 438: 'Mime Jr.',
 439: 'Happiny',
 440: 'Chatot',
 441: 'Spiritomb',
 442: 'Gible',
 443: 'Gabite',
 444: 'Garchomp',
 445: 'Munchlax',
 446: 'Riolu',
 447: 'Lucario',
 448: 'Hippopotas',
 449: 'Hippowdon',
 450: 'Skorupi',
 451: 'Drapion',
 452: 'Croagunk',
 453: 'Toxicroak',
 454: 'Carnivine',
 455: 'Finneon',
 456: 'Lumineon',
 457: 'Mantyke',
 458: 'Snover',
 459: 'Abomasnow',
 460: 'Weavile',
 461: 'Magnezone',
 462: 'Lickilicky',
 463: 'Rhyperior',
 464: 'Tangrowth',
 465: 'Electivire',
 466: 'Magmortar',
 467: 'Togekiss',
 468: 'Yanmega',
 469: 'Leafeon',
 470: 'Glaceon',
 471: 'Gliscor',
 472: 'Mamoswine',
 473: 'Porygon-Z',
 474: 'Gallade',
 475: 'Probopass',
 476: 'Dusknoir',
 477: 'Froslass',
 478: 'Rotom',
 479: 'Uxie',
 480: 'Mesprit',
 481: 'Azelf',
 482: 'Dialga',
 483: 'Palkia',
 484: 'Heatran',
 485: 'Regigigas',
 486: 'Giratina',
 487: 'Cresselia',
 488: 'Phione',
 489: 'Manaphy',
 490: 'Darkrai',
 491: 'Shaymin',
 492: 'Arceus',
 493: 'Victini',
 494: 'Snivy',
 495: 'Servine',
 496: 'Serperior',
 497: 'Tepig',
 498: 'Pignite',
 499: 'Emboar',
 500: 'Oshawott',
 501: 'Dewott',
 502: 'Samurott',
 503: 'Patrat',
 504: 'Watchog',
 505: 'Lillipup',
 506: 'Herdier',
 507: 'Stoutland',
 508: 'Purrloin',
 509: 'Liepard',
 510: 'Pansage',
 511: 'Simisage',
 512: 'Pansear',
 513: 'Simisear',
 514: 'Panpour',
 515: 'Simipour',
 516: 'Munna',
 517: 'Musharna',
 518: 'Pidove',
 519: 'Tranquill',
 520: 'Unfezant',
 521: 'Blitzle',
 522: 'Zebstrika',
 523: 'Roggenrola',
 524: 'Boldore',
 525: 'Gigalith',
 526: 'Woobat',
 527: 'Swoobat',
 528: 'Drilbur',
 529: 'Excadrill',
 530: 'Audino',
 531: 'Timburr',
 532: 'Gurdurr',
 533: 'Conkeldurr',
 534: 'Tympole',
 535: 'Palpitoad',
 536: 'Seismitoad',
 537: 'Throh',
 538: 'Sawk',
 539: 'Sewaddle',
 540: 'Swadloon',
 541: 'Leavanny',
 542: 'Venipede',
 543: 'Whirlipede',
 544: 'Scolipede',
 545: 'Cottonee',
 546: 'Whimsicott',
 547: 'Petilil',
 548: 'Lilligant',
 549: 'Basculin',
 550: 'Sandile',
 551: 'Krokorok',
 552: 'Krookodile',
 553: 'Darumaka',
 554: 'Darmanitan',
 555: 'Maractus',
 556: 'Dwebble',
 557: 'Crustle',
 558: 'Scraggy',
 559: 'Scrafty',
 560: 'Sigilyph',
 561: 'Yamask',
 562: 'Cofagrigus',
 563: 'Tirtouga',
 564: 'Carracosta',
 565: 'Archen',
 566: 'Archeops',
 567: 'Trubbish',
 568: 'Garbodor',
 569: 'Zorua',
 570: 'Zoroark',
 571: 'Minccino',
 572: 'Cinccino',
 573: 'Gothita',
 574: 'Gothorita',
 575: 'Gothitelle',
 576: 'Solosis',
 577: 'Duosion',
 578: 'Reuniclus',
 579: 'Ducklett',
 580: 'Swanna',
 581: 'Vanillite',
 582: 'Vanillish',
 583: 'Vanilluxe',
 584: 'Deerling',
 585: 'Sawsbuck',
 586: 'Emolga',
 587: 'Karrablast',
 588: 'Escavalier',
 589: 'Foongus',
 590: 'Amoonguss',
 591: 'Frillish',
 592: 'Jellicent',
 593: 'Alomomola',
 594: 'Joltik',
 595: 'Galvantula',
 596: 'Ferroseed',
 597: 'Ferrothorn',
 598: 'Klink',
 599: 'Klang',
 600: 'Klinklang',
 601: 'Tynamo',
 602: 'Eelektrik',
 603: 'Eelektross',
 604: 'Elgyem',
 605: 'Beheeyem',
 606: 'Litwick',
 607: 'Lampent',
 608: 'Chandelure',
 609: 'Axew',
 610: 'Fraxure',
 611: 'Haxorus',
 612: 'Cubchoo',
 613: 'Beartic',
 614: 'Cryogonal',
 615: 'Shelmet',
 616: 'Accelgor',
 617: 'Stunfisk',
 618: 'Mienfoo',
 619: 'Mienshao',
 620: 'Druddigon',
 621: 'Golett',
 622: 'Golurk',
 623: 'Pawniard',
 624: 'Bisharp',
 625: 'Bouffalant',
 626: 'Rufflet',
 627: 'Braviary',
 628: 'Vullaby',
 629: 'Mandibuzz',
 630: 'Heatmor',
 631: 'Durant',
 632: 'Deino',
 633: 'Zweilous',
 634: 'Hydreigon',
 635: 'Larvesta',
 636: 'Volcarona',
 637: 'Cobalion',
 638: 'Terrakion',
 639: 'Virizion',
 640: 'Tornadus',
 641: 'Thundurus',
 642: 'Reshiram',
 643: 'Zekrom',
 644: 'Landorus',
 645: 'Kyurem',
 646: 'Keldeo',
 647: 'Meloetta',
 648: 'Genesect',
 649: 'Chespin',
 650: 'Quilladin',
 651: 'Chesnaught',
 652: 'Fennekin',
 653: 'Braixen',
 654: 'Delphox',
 655: 'Froakie',
 656: 'Frogadier',
 657: 'Greninja',
 658: 'Bunnelby',
 659: 'Diggersby',
 660: 'Fletchling',
 661: 'Fletchinder',
 662: 'Talonflame',
 663: 'Scatterbug',
 664: 'Spewpa',
 665: 'Vivillon',
 666: 'Litleo',
 667: 'Pyroar',
 668: 'Flabébé',
 669: 'Floette',
 670: 'Florges',
 671: 'Skiddo',
 672: 'Gogoat',
 673: 'Pancham',
 674: 'Pangoro',
 675: 'Furfrou',
 676: 'Espurr',
 677: 'Meowstic',
 678: 'Honedge',
 679: 'Doublade',
 680: 'Aegislash',
 681: 'Spritzee',
 682: 'Aromatisse',
 683: 'Swirlix',
 684: 'Slurpuff',
 685: 'Inkay',
 686: 'Malamar',
 687: 'Binacle',
 688: 'Barbaracle',
 689: 'Skrelp',
 690: 'Dragalge',
 691: 'Clauncher',
 692: 'Clawitzer',
 693: 'Helioptile',
 694: 'Heliolisk',
 695: 'Tyrunt',
 696: 'Tyrantrum',
 697: 'Amaura',
 698: 'Aurorus',
 699: 'Sylveon',
 700: 'Hawlucha',
 701: 'Dedenne',
 702: 'Carbink',
 703: 'Goomy',
 704: 'Sliggoo',
 705: 'Goodra',
 706: 'Klefki',
 707: 'Phantump',
 708: 'Trevenant',
 709: 'Pumpkaboo',
 710: 'Gourgeist',
 711: 'Bergmite',
 712: 'Avalugg',
 713: 'Noibat',
 714: 'Noivern',
 715: 'Xerneas',
 716: 'Yveltal',
 717: 'Zygarde',
 718: 'Diancie',
 719: 'Hoopa',
 720: 'Volcanion',
 721: 'Rowlet',
 722: 'Dartrix',
 723: 'Decidueye',
 724: 'Litten',
 725: 'Torracat',
 726: 'Incineroar',
 727: 'Popplio',
 728: 'Brionne',
 729: 'Primarina',
 730: 'Pikipek',
 731: 'Trumbeak',
 732: 'Toucannon',
 733: 'Yungoos',
 734: 'Gumshoos',
 735: 'Grubbin',
 736: 'Charjabug',
 737: 'Vikavolt',
 738: 'Crabrawler',
 739: 'Crabominable',
 740: 'Oricorio',
 741: 'Cutiefly',
 742: 'Ribombee',
 743: 'Rockruff',
 744: 'Lycanroc',
 745: 'Wishiwashi',
 746: 'Mareanie',
 747: 'Toxapex',
 748: 'Mudbray',
 749: 'Mudsdale',
 750: 'Dewpider',
 751: 'Araquanid',
 752: 'Fomantis',
 753: 'Lurantis',
 754: 'Morelull',
 755: 'Shiinotic',
 756: 'Salandit',
 757: 'Salazzle',
 758: 'Stufful',
 759: 'Bewear',
 760: 'Bounsweet',
 761: 'Steenee',
 762: 'Tsareena',
 763: 'Comfey',
 764: 'Oranguru',
 765: 'Passimian',
 766: 'Wimpod',
 767: 'Golisopod',
 768: 'Sandygast',
 769: 'Palossand',
 770: 'Pyukumuku',
 771: 'Type: Null',
 772: 'Silvally',
 773: 'Minior',
 774: 'Komala',
 775: 'Turtonator',
 776: 'Togedemaru',
 777: 'Mimikyu',
 778: 'Bruxish',
 779: 'Drampa',
 780: 'Dhelmise',
 781: 'Jangmo-o',
 782: 'Hakamo-o',
 783: 'Kommo-o',
 784: 'Tapu Koko',
 785: 'Tapu Lele',
 786: 'Tapu Bulu',
 787: 'Tapu Fini',
 788: 'Cosmog',
 789: 'Cosmoem',
 790: 'Solgaleo',
 791: 'Lunala',
 792: 'Nihilego',
 793: 'Buzzwole',
 794: 'Pheromosa',
 795: 'Xurkitree',
 796: 'Celesteela',
 797: 'Kartana',
 798: 'Guzzlord',
 799: 'Necrozma',
 800: 'Magearna',
 801: 'Marshadow',
 802: 'Poipole',
 803: 'Naganadel',
 804: 'Stakataka',
 805: 'Blacephalon',
 806: 'Zeraora',
 807: 'Meltan',
 808: 'Melmetal',
 809: 'Grookey',
 810: 'Thwackey',
 811: 'Rillaboom',
 812: 'Scorbunny',
 813: 'Raboot',
 814: 'Cinderace',
 815: 'Sobble',
 816: 'Drizzile',
 817: 'Inteleon',
 818: 'Skwovet',
 819: 'Greedent',
 820: 'Rookidee',
 821: 'Corvisquire',
 822: 'Corviknight',
 823: 'Blipbug',
 824: 'Dottler',
 825: 'Orbeetle',
 826: 'Nickit',
 827: 'Thievul',
 828: 'Gossifleur',
 829: 'Eldegoss',
 830: 'Wooloo',
 831: 'Dubwool',
 832: 'Chewtle',
 833: 'Drednaw',
 834: 'Yamper',
 835: 'Boltund',
 836: 'Rolycoly',
 837: 'Carkol',
 838: 'Coalossal',
 839: 'Applin',
 840: 'Flapple',
 841: 'Appletun',
 842: 'Silicobra',
 843: 'Sandaconda',
 844: 'Cramorant',
 845: 'Arrokuda',
 846: 'Barraskewda',
 847: 'Toxel',
 848: 'Toxtricity',
 849: 'Sizzlipede',
 850: 'Centiskorch',
 851: 'Clobbopus',
 852: 'Grapploct',
 853: 'Sinistea',
 854: 'Polteageist',
 855: 'Hatenna',
 856: 'Hattrem',
 857: 'Hatterene',
 858: 'Impidimp',
 859: 'Morgrem',
 860: 'Grimmsnarl',
 861: 'Obstagoon',
 862: 'Perrserker',
 863: 'Cursola',
 864: 'Sirfetch’d',
 865: 'Mr. Rime',
 866: 'Runerigus',
 867: 'Milcery',
 868: 'Alcremie',
 869: 'Falinks',
 870: 'Pincurchin',
 871: 'Snom',
 872: 'Frosmoth',
 873: 'Stonjourner',
 874: 'Eiscue',
 875: 'Indeedee',
 876: 'Morpeko',
 877: 'Cufant',
 878: 'Copperajah',
 879: 'Dracozolt',
 880: 'Arctozolt',
 881: 'Dracovish',
 882: 'Arctovish',
 883: 'Duraludon',
 884: 'Dreepy',
 885: 'Drakloak',
 886: 'Dragapult',
 887: 'Zacian',
 888: 'Zamazenta',
 889: 'Eternatus',
 890: 'Kubfu',
 891: 'Urshifu',
 892: 'Zarude',
 893: 'Regieleki',
 894: 'Regidrago',
 895: 'Glastrier',
 896: 'Spectrier',
 897: 'Calyrex',
 898: 'Wyrdeer',
 899: 'Kleavor',
 900: 'Ursaluna',
 901: 'Basculegion',
 902: 'Sneasler',
 903: 'Overqwil',
 904: 'Enamorus',
 905: 'Sprigatito',
 906: 'Floragato',
 907: 'Meowscarada',
 908: 'Fuecoco',
 909: 'Crocalor',
 910: 'Skeledirge',
 911: 'Quaxly',
 912: 'Quaxwell',
 913: 'Quaquaval',
 914: 'Lechonk',
 915: 'Oinkologne',
 916: 'Tarountula',
 917: 'Spidops',
 918: 'Nymble',
 919: 'Lokix',
 920: 'Pawmi',
 921: 'Pawmo',
 922: 'Pawmot',
 923: 'Tandemaus',
 924: 'Maushold',
 925: 'Fidough',
 926: 'Dachsbun',
 927: 'Smoliv',
 928: 'Dolliv',
 929: 'Arboliva',
 930: 'Squawkabilly',
 931: 'Nacli',
 932: 'Naclstack',
 933: 'Garganacl',
 934: 'Charcadet',
 935: 'Armarouge',
 936: 'Ceruledge',
 937: 'Tadbulb',
 938: 'Bellibolt',
 939: 'Wattrel',
 940: 'Kilowattrel',
 941: 'Maschiff',
 942: 'Mabosstiff',
 943: 'Shroodle',
 944: 'Grafaiai',
 945: 'Bramblin',
 946: 'Brambleghast',
 947: 'Toedscool',
 948: 'Toedscruel',
 949: 'Klawf',
 950: 'Capsakid',
 951: 'Scovillain',
 952: 'Rellor',
 953: 'Rabsca',
 954: 'Flittle',
 955: 'Espathra',
 956: 'Tinkatink',
 957: 'Tinkatuff',
 958: 'Tinkaton',
 959: 'Wiglett',
 960: 'Wugtrio',
 961: 'Bombirdier',
 962: 'Finizen',
 963: 'Palafin',
 964: 'Varoom',
 965: 'Revavroom',
 966: 'Cyclizar',
 967: 'Orthworm',
 968: 'Glimmet',
 969: 'Glimmora',
 970: 'Greavard',
 971: 'Houndstone',
 972: 'Flamigo',
 973: 'Cetoddle',
 974: 'Cetitan',
 975: 'Veluza',
 976: 'Dondozo',
 977: 'Tatsugiri',
 978: 'Annihilape',
 979: 'Clodsire',
 980: 'Farigiraf',
 981: 'Dudunsparce',
 982: 'Kingambit',
 983: 'Great Tusk',
 984: 'Scream Tail',
 985: 'Brute Bonnet',
 986: 'Flutter Mane',
 987: 'Slither Wing',
 988: 'Sandy Shocks',
 989: 'Iron Treads',
 990: 'Iron Bundle',
 991: 'Iron Hands',
 992: 'Iron Jugulis',
 993: 'Iron Moth',
 994: 'Iron Thorns',
 995: 'Frigibax',
 996: 'Arctibax',
 997: 'Baxcalibur',
 998: 'Gimmighoul',
 999: 'Gholdengo',
 ...}

In [56]:
max(google)

3025.0

In [ ]:
min(google)

In [58]:
# max and min function returns the first and last element of the sorted series of pokemon
max(pokemon)

'Zygarde'

In [57]:
min(pokemon)

'Abomasnow'

## Check for Inclusion with Python's in Keyword
- The `in` keyword checks if a value exists within an object.
- But in pandas, It checks the index, not the values.
- The values can be checked through two method:
- print("Bulbasaur" in pokemon.values) method 1
- print(pokemon.isin(["Bulbasaur"]).any()) method 2
- The `in` keyword will look for a value in the **Series's** index.
- Use the `index` and `values` attributes to access "nested" objects within the **Series**.
- Combine the `in` keyword with `values` to search within the **Series's** values.

In [22]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [28]:
print("car" in "racecar")
print(2 in [3, 2, 1])
# in keyword returns true if whether the searched value is in indexes or values when we are just using the series name

print("Bulbasaur" in pokemon)
print(5 in pokemon.index)
print(5 in pokemon.values)

print("Bulbasaur" in pokemon.values)
print("Pikachu" in pokemon.values)
print("Nonsense" in pokemon.values)

True
True
False
True
False
True
True
False

In [27]:
print("Bulbasaur" in pokemon)
pokemon.head()

False

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [66]:
0 in pokemon.index

True

## The sort_values Method
- Pandas series can be sorted using python function list however doing so doesn't changes the origingal series
- the sort_values also do not changes the original series
- The `sort_values` method sorts a **Series** values in order.
- By default, pandas applies an ascending sort (smallest to largest).
- Customize the sort order with the `ascending` parameter.

In [32]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_price.csv", usecols=["1. open"]).squeeze("columns")

google.head()

0    169.055
1    171.850
2    163.690
3    166.430
4    164.510
Name: 1. open, dtype: float64

In [33]:
print(google.sort_values())
print(google.sort_values(ascending=True))
print(google.sort_values(ascending=False))
print(google.sort_values(ascending=False).head())

638      85.4000
594      85.9800
639      86.3200
601      86.6200
596      86.7900
         ...
887    2984.6600
878    2986.6500
888    2996.5000
879    2999.5088
829    3025.0000
Name: 1. open, Length: 5225, dtype: float64
638      85.4000
594      85.9800
639      86.3200
601      86.6200
596      86.7900
         ...
887    2984.6600
878    2986.6500
888    2996.5000
879    2999.5088
829    3025.0000
Name: 1. open, Length: 5225, dtype: float64
829    3025.0000
879    2999.5088
888    2996.5000
878    2986.6500
887    2984.6600
         ...
596      86.7900
601      86.6200
639      86.3200
594      85.9800
638      85.4000
Name: 1. open, Length: 5225, dtype: float64
829    3025.0000
879    2999.5088
888    2996.5000
878    2986.6500
887    2984.6600
Name: 1. open, dtype: float64

In [34]:
print(pokemon.sort_values())
print(pokemon.sort_values(ascending=True))
print(pokemon.sort_values(ascending=False))
print(pokemon.sort_values(ascending=True).tail())

459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
         ...
570      Zoroark
569        Zorua
40         Zubat
633     Zweilous
717      Zygarde
Name: Name, Length: 1010, dtype: str
459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
         ...
570      Zoroark
569        Zorua
40         Zubat
633     Zweilous
717      Zygarde
Name: Name, Length: 1010, dtype: str
717      Zygarde
633     Zweilous
40         Zubat
569        Zorua
570      Zoroark
         ...
680    Aegislash
616     Accelgor
358        Absol
62          Abra
459    Abomasnow
Name: Name, Length: 1010, dtype: str
570     Zoroark
569       Zorua
40        Zubat
633    Zweilous
717     Zygarde
Name: Name, dtype: str

## The sort_index Method
- The `sort_index` method sorts a **Series** by its index.
- The `sort_index` method also accepts an `ascending` parameter to set sort order.

In [38]:
# pd.read_csv() reads the CSV file into a DataFrame.
# index_col="Name" makes the Name column the index (labels).
# Now only the Type column remains as data.
# .squeeze("columns") converts the single-column DataFrame into a Series.
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [39]:
print(pokemon.sort_index())
print(pokemon.sort_index(ascending=True))
print(pokemon.sort_index(ascending=False))

Name
Abomasnow        Grass, Ice
Abra                Psychic
Absol                  Dark
Accelgor                Bug
Aegislash      Steel, Ghost
                  ...
Zoroark                Dark
Zorua                  Dark
Zubat        Poison, Flying
Zweilous       Dark, Dragon
Zygarde      Dragon, Ground
Name: Type, Length: 1010, dtype: str
Name
Abomasnow        Grass, Ice
Abra                Psychic
Absol                  Dark
Accelgor                Bug
Aegislash      Steel, Ghost
                  ...
Zoroark                Dark
Zorua                  Dark
Zubat        Poison, Flying
Zweilous       Dark, Dragon
Zygarde      Dragon, Ground
Name: Type, Length: 1010, dtype: str
Name
Zygarde      Dragon, Ground
Zweilous       Dark, Dragon
Zubat        Poison, Flying
Zorua                  Dark
Zoroark                Dark
                  ...
Aegislash      Steel, Ghost
Accelgor                Bug
Absol                  Dark
Abra                Psychic
Abomasnow        Grass, Ice
Name: Type, Length: 1010, dtype: str

## Extract Series Value by Index Position
- Use the `iloc` accessor to extract a **Series** value by its index position.
- `iloc` is short for "index location".
- Python's list slicing syntaxes (slices, slices from start, slices to end, etc.) are supported with **Series** objects.

loc and iloc are two of the most important indexing methods in Pandas. The difference is simple:

loc → Access data using labels (index names).
iloc → Access data using integer positions (0, 1, 2, ...).
    
1. loc (Label-based Indexing)
Definition

loc is used to access data by its index label (name).

2.iloc (Integer Position-based Indexing)
Definition

iloc is used to access data by its integer position.
While slicing,
Important: loc includes the ending label.
Important: iloc excludes the ending position (like normal Python slicing).

In [40]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [43]:
print(pokemon.iloc[0])
print(pokemon.iloc[500])

# pokemon.iloc[1500])

print(pokemon.iloc[[100, 200, 300]])

# pokemon.iloc[[100, 200, 300, 1500]])

print(pokemon.iloc[27:36])
print(pokemon.iloc[0:7])
print(pokemon.iloc[:7])

print(pokemon.iloc[700:1010])
print(pokemon.iloc[700:])
print(pokemon.iloc[700:5000])

print(pokemon.iloc[-1])
print(pokemon.iloc[-10])

print(pokemon.iloc[-10:-5])
print(pokemon.iloc[-8:])

Bulbasaur
Oshawott
100    Electrode
200        Unown
300     Delcatty
Name: Name, dtype: str
27    Sandslash
28     Nidoran♀
29     Nidorina
30    Nidoqueen
31     Nidoran♂
32     Nidorino
33     Nidoking
34     Clefairy
35     Clefable
Name: Name, dtype: str
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
Name: Name, dtype: str
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
Name: Name, dtype: str
700         Hawlucha
701          Dedenne
702          Carbink
703            Goomy
704          Sliggoo
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 310, dtype: str
700         Hawlucha
701          Dedenne
702          Carbink
703            Goomy
704          Sliggoo
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 310, dtype: str
700         Hawlucha
701          Dedenne
702          Carbink
703            Goomy
704          Sliggoo
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 310, dtype: str
Iron Leaves
Wo-Chien
1000        Wo-Chien
1001       Chien-Pao
1002         Ting-Lu
1003          Chi-Yu
1004    Roaring Moon
Name: Name, dtype: str
1002         Ting-Lu
1003          Chi-Yu
1004    Roaring Moon
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, dtype: str

## Extract Series Value by Index Label
- Use the `loc` accessor to extract a **Series** value by its index label.
- Pass a list to extract multiple values by index label.
- If one index label/position in the list does not exist, Pandas will raise an error.

In [45]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [46]:
pokemon.loc["Bulbasaur"]

'Grass, Poison'

In [49]:
pokemon.iloc[0]

'Grass, Poison'

In [50]:
print(pokemon.loc["Mewtwo"])
print(pokemon.loc[["Charizard", "Jolteon", "Meowth"]])

# pokemon.loc["Digimon"]

# pokemon.loc[["Pikachu", "Digimon"]]

Psychic
Name
Charizard    Fire, Flying
Jolteon          Electric
Meowth             Normal
Name: Type, dtype: str

## The get Method on a Series
- The `get` method extracts a **Series** value by index label. It is an alternative option to square brackets.
- The `get` method's second argument sets the fallback value to return if the label/position does not exist.

In [51]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [54]:
print(pokemon.get("Moltres"))
print(pokemon.loc["Moltres"])

# pokemon.loc["Digimon"]
print(pokemon.get("Digimon"))
print(pokemon.get("Digimon", "Nonexistent"))#digimon doesn't exist so it sets nonexistent in its values and creates new index digimon as well
                                             # and returns the same set value
print(pokemon.get("Moltres", "Nonexistent"))

print(pokemon.get(["Moltres", "Digimon"], "One of the values in the list was not found so setting the fallback value which sets the value and returns the same value"))

Fire, Flying
Fire, Flying
None
Nonexistent
Fire, Flying
One of the values in the list was not found so setting the fallback value which sets the value and returns the same value

s = pd.Series([100, 200, 300], index=[10, 20, 30])

Now what should this mean?

s[10]

Is 10:

the index label?
or the 10th position?

Pandas interprets it as the label.

To avoid confusion:

s.loc[10]    # Label 10 → 100
s.iloc[0]    # First position → 100

Now your code clearly shows your intention.

## Overwrite a Series Value
- Use the `loc/iloc` accessor to target an index label/position, then use an equal sign to provide a new value.
- We can use the slicing without loc or iloc to change the value but as listed above it may create confusion

In [ ]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon.head()

In [56]:
# changing the value of series
pokemon.iloc[0] = "Borisaur"
print(pokemon.head())

Name
Bulbasaur          Borisaur
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [57]:
pokemon.head()

Name
Bulbasaur          Borisaur
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [58]:
# for multiple accessing we need to use two brackets
pokemon.iloc[[1, 2, 4]] = ["Firemon", "Flamemon", "Blazemon"]

In [59]:
pokemon.head()

Name
Bulbasaur     Borisaur
Ivysaur        Firemon
Venusaur      Flamemon
Charmander        Fire
Charmeleon    Blazemon
Name: Type, dtype: str

In [60]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [61]:
# this is using loc
pokemon.loc["Bulbasaur"] = "Awesomeness"

In [62]:
pokemon.head()

Name
Bulbasaur       Awesomeness
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [65]:
# this is using iloc
pokemon.iloc[1] = "Silly"

In [64]:
pokemon.head()

Name
Bulbasaur       Awesomeness
Ivysaur               Silly
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

## The copy Method
- A **copy** is a duplicate/replica of an object.
- Changes to a copy do not modify the original object.
- A **view** is a different way of looking at the *same* data.
- Changes to a view *do* modify the original object.
- The `copy` method creates a copy of a pandas object.

In [75]:
# usiing copy method
pokemon_df = pd.read_csv("pokemon.csv", usecols=["Name"])
pokemon_series = pokemon_df.squeeze("columns")
pokemon_series_copy = pokemon_df.squeeze("columns").copy()

In [67]:
pokemon_df

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

In [68]:
pokemon_series

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

In [76]:
# changing the vlaue of 0 index of copied pokemon
print("Before change = ", pokemon_series.head())
print("Before change = ", pokemon_series_copy.head())
pokemon_series_copy[0] = "Whatever"
print("After change = ", pokemon_series.head())
print("After change = ", pokemon_series_copy.head())

Before change =  0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
Before change =  0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
After change =  0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str
After change =  0      Whatever
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [77]:
pokemon_series_copy.head()

0      Whatever
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [78]:
pokemon_df

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

## Math Methods on Series Objects
- The `count` method returns the number of values in the **Series**. It excludes missing values; the `size` attribute includes missing values.
- The `sum` method adds together the **Series's** values.
- The `product` method multiplies together the **Series's** values.
- The `mean` method calculates the average of the **Series's** values.
- The `std` method calculates the standard deviation of the **Series's** values.
- The `max` method returns the largest value in the **Series**.
- The `min` method returns the smallest value in the **Series**.
- The `median` method returns the median of the **Series** (the value in the middle).
- The `mode` method returns the mode of the **Series** (the most frequent alue).
- The `describe` method returns a summary with various mathematical calculations
- .The `info` method displays a summary of the Series, including its index, number of non-null values, data type, memory usage, and the Series name (if available).

In [81]:
google = pd.read_csv("google_stock_price.csv", usecols=["1. open"]).squeeze("columns")
google.head()

0    169.055
1    171.850
2    163.690
3    166.430
4    164.510
Name: 1. open, dtype: float64

In [ ]:
print(google.count())
print(google.sum())
print(google.product())
print(pd.Series([1, 2, 3, 4]).product())
print(google.mean())
print(google.std())

In [88]:
print(google.max())
print(google.min())
print(google.median())
print(google.mode())
print(pd.Series([1, 2, 2, 2, 3]).mode())

print(google.describe())
print(google.info())

3025.0
85.4
585.98
0      119.24
1      138.50
2      169.00
3      460.00
4      525.00
5      526.52
6      540.00
7      544.00
8      547.00
9      563.00
10     567.00
11     568.00
12     569.50
13     575.00
14     591.00
15     595.00
16     615.00
17     680.00
18    1160.00
Name: 1. open, dtype: float64
0    2
dtype: int64
count    5225.000000
mean      764.930355
std       612.984170
min        85.400000
25%       400.300000
50%       585.980000
75%      1001.000000
max      3025.000000
Name: 1. open, dtype: float64
<class 'pandas.Series'>
RangeIndex: 5225 entries, 0 to 5224
Series name: 1. open
Non-Null Count  Dtype
--------------  -----
5225 non-null   float64
dtypes: float64(1)
memory usage: 40.9 KB
None

## Broadcasting
- **Broadcasting** describes the process of applying an arithmetic operation to an array (i.e., a **Series**).
- We can combine mathematical operators with a **Series** to apply the mathematical operation to every value.
- There are also methods to accomplish the same results (`add`, `sub`, `mul`, `div`, etc.)

In [85]:
google = pd.read_csv("google_stock_price.csv", usecols=["1. open"]).squeeze("columns")
google.head()

0    169.055
1    171.850
2    163.690
3    166.430
4    164.510
Name: 1. open, dtype: float64

In [86]:
print(google.add(10))
print(google + 10)

print(google.sub(30))
print(google - 30)

print(google.mul(1.25))
print(google * 1.25)
print(1.25 * google)

print(google.div(2))
print(google / 2)

0       179.055
1       181.850
2       173.690
3       176.430
4       174.510
         ...
5220    114.760
5221    121.240
5222    120.760
5223    111.010
5224    110.010
Name: 1. open, Length: 5225, dtype: float64
0       179.055
1       181.850
2       173.690
3       176.430
4       174.510
         ...
5220    114.760
5221    121.240
5222    120.760
5223    111.010
5224    110.010
Name: 1. open, Length: 5225, dtype: float64
0       139.055
1       141.850
2       133.690
3       136.430
4       134.510
         ...
5220     74.760
5221     81.240
5222     80.760
5223     71.010
5224     70.010
Name: 1. open, Length: 5225, dtype: float64
0       139.055
1       141.850
2       133.690
3       136.430
4       134.510
         ...
5220     74.760
5221     81.240
5222     80.760
5223     71.010
5224     70.010
Name: 1. open, Length: 5225, dtype: float64
0       211.31875
1       214.81250
2       204.61250
3       208.03750
4       205.63750
          ...
5220    130.95000
5221    139.05000
5222    138.45000
5223    126.26250
5224    125.01250
Name: 1. open, Length: 5225, dtype: float64
0       211.31875
1       214.81250
2       204.61250
3       208.03750
4       205.63750
          ...
5220    130.95000
5221    139.05000
5222    138.45000
5223    126.26250
5224    125.01250
Name: 1. open, Length: 5225, dtype: float64
0       211.31875
1       214.81250
2       204.61250
3       208.03750
4       205.63750
          ...
5220    130.95000
5221    139.05000
5222    138.45000
5223    126.26250
5224    125.01250
Name: 1. open, Length: 5225, dtype: float64
0       84.5275
1       85.9250
2       81.8450
3       83.2150
4       82.2550
         ...
5220    52.3800
5221    55.6200
5222    55.3800
5223    50.5050
5224    50.0050
Name: 1. open, Length: 5225, dtype: float64
0       84.5275
1       85.9250
2       81.8450
3       83.2150
4       82.2550
         ...
5220    52.3800
5221    55.6200
5222    55.3800
5223    50.5050
5224    50.0050
Name: 1. open, Length: 5225, dtype: float64

## The value_counts Method
- The `value_counts` method returns the number of times each unique value occurs in the **Series**.
- The `normalize` parameter returns the relative frequencies/percentages of the values instead of the counts.

In [89]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [91]:
print(pokemon.value_counts())
print(pokemon.value_counts(ascending=True))
print(pokemon.value_counts(normalize=True))
print(pokemon.value_counts(normalize=True) * 100)

Type
Water               74
Normal              74
Grass               46
Psychic             39
Fire                36
                    ..
Rock, Electric       1
Dark, Ground         1
Dragon, Dark         1
Fairy, Fighting      1
Fighting, Dragon     1
Name: count, Length: 200, dtype: int64
Type
Steel, Ground     1
Fire, Rock        1
Rock, Dark        1
Bug, Ground       1
Bug, Ghost        1
                 ..
Fire             36
Psychic          39
Grass            46
Water            74
Normal           74
Name: count, Length: 200, dtype: int64
Type
Water               0.073267
Normal              0.073267
Grass               0.045545
Psychic             0.038614
Fire                0.035644
                      ...
Rock, Electric      0.000990
Dark, Ground        0.000990
Dragon, Dark        0.000990
Fairy, Fighting     0.000990
Fighting, Dragon    0.000990
Name: proportion, Length: 200, dtype: float64
Type
Water               7.326733
Normal              7.326733
Grass               4.554455
Psychic             3.861386
Fire                3.564356
                      ...
Rock, Electric      0.099010
Dark, Ground        0.099010
Dragon, Dark        0.099010
Fairy, Fighting     0.099010
Fighting, Dragon    0.099010
Name: proportion, Length: 200, dtype: float64

## The apply Method
- The `apply` method accepts a function. It invokes that function on every `Series` value.

In [92]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [94]:
# it applies len function to each value of series
pokemon.apply(len)

0        9
1        7
2        8
3       10
4       10
        ..
1005    12
1006     8
1007     8
1008    12
1009    11
Name: Name, Length: 1010, dtype: int64

In [95]:
def count_of_a(pokemon):
    return pokemon.count("a")

pokemon.apply(count_of_a)

0       2
1       1
2       1
3       2
4       1
       ..
1005    2
1006    1
1007    1
1008    2
1009    1
Name: Name, Length: 1010, dtype: int64

## The map Method
- The `map` method "maps" or connects each **Series** values to another value.
- We can pass the method a dictionary or a **Series**. Both types connects keys to values.
- The `map` method uses our argument to connect or bridge together the values.

In [96]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon

Name
Bulbasaur          Grass, Poison
Ivysaur            Grass, Poison
Venusaur           Grass, Poison
Charmander                  Fire
Charmeleon                  Fire
                      ...
Iron Valiant     Fairy, Fighting
Koraidon        Fighting, Dragon
Miraidon        Electric, Dragon
Walking Wake       Water, Dragon
Iron Leaves       Grass, Psychic
Name: Type, Length: 1010, dtype: str

In [100]:
# creating another series whose keys are same as the value of the pokemon series
attack_powers = pd.Series({
    "Grass, Poison": 10,
    "Fire": 15,
    "Water": 15,
    "Fairy, Fighting": 20,
    "Grass, Psychic": 50
})

attack_powers

Grass, Poison      10
Fire               15
Water              15
Fairy, Fighting    20
Grass, Psychic     50
dtype: int64

In [101]:
# map method sees whether the key value of attack_powers are same as the values of the series pokemon
# and if yes then it sets the new value i.e the values of the corresponding matched key in the place of that matched value
pokemon.map(attack_powers)

Name
Bulbasaur       10.0
Ivysaur         10.0
Venusaur        10.0
Charmander      15.0
Charmeleon      15.0
                ...
Iron Valiant    20.0
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves     50.0
Name: Type, Length: 1010, dtype: float64